#!/bin/bash

#SBATCH --job-name=job_MLIPTS
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:20:00

#SBATCH --account=e89-camm
#SBATCH --partition=standard
#SBATCH --qos=short
    
directories="./MD_calculations/lammps_T_100 ./MD_calculations/lammps_T_200 "
for i in $directories; 
do 
cd $i
srun --distribution=block:block --hint=nomultithread /work/e89/e89/wd324/Programs/lammps/build/lmp -in in.PuO2 -out out.PuO2
cd -


done
