#!/bin/bash

#SBATCH --job-name=lammps_test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:20:00

#SBATCH --account=e89-camm
#SBATCH --partition=standard
#SBATCH --qos=standard
    
directories="PuO2_T_100 PuO2_T_200 "
cd .
for i in $directories; 
do 
cd $i
    srun --distribution=block:block --hint=nomultithread /work/e89/e89/wd324/Programs/lammps/build/lmp -i in.PuO2 -l out.PuO2
cd ..
done
cd ..