#!/bin/bash

#SBATCH --job-name=job_MLIPTS
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:20:00

#SBATCH --account=my_account
#SBATCH --partition=standard
#SBATCH --qos=short
    
directories="./MD_calculations/lammps_T_100 ./MD_calculations/lammps_T_200 "
for i in $directories; 
do 
cd $i
srun --distribution=block:block --hint=nomultithread path/to/lammps/build/lmp -i in.PuO2 -l out.PuO2
cd -


done
